<?php
/**
 * OrderItem20211228
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * The version of the OpenAPI document: 2021-12-28
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model;

use \Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * OrderItem20211228 Class Doc Comment
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class OrderItem20211228 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrderItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'itemSequenceNumber' => 'string',
        'buyerProductIdentifier' => 'string',
        'vendorProductIdentifier' => 'string',
        'title' => 'string',
        'orderedQuantity' => '\Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\ItemQuantity20211228',
        'scheduledDeliveryShipment' => '\Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\ScheduledDeliveryShipment20211228',
        'giftDetails' => '\Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\GiftDetails20211228',
        'netPrice' => '\Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\Money20211228',
        'taxDetails' => '\Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\TaxItemDetails20211228',
        'totalPrice' => '\Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\Money20211228'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'itemSequenceNumber' => null,
        'buyerProductIdentifier' => null,
        'vendorProductIdentifier' => null,
        'title' => null,
        'orderedQuantity' => null,
        'scheduledDeliveryShipment' => null,
        'giftDetails' => null,
        'netPrice' => null,
        'taxDetails' => null,
        'totalPrice' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'itemSequenceNumber' => 'itemSequenceNumber',
        'buyerProductIdentifier' => 'buyerProductIdentifier',
        'vendorProductIdentifier' => 'vendorProductIdentifier',
        'title' => 'title',
        'orderedQuantity' => 'orderedQuantity',
        'scheduledDeliveryShipment' => 'scheduledDeliveryShipment',
        'giftDetails' => 'giftDetails',
        'netPrice' => 'netPrice',
        'taxDetails' => 'taxDetails',
        'totalPrice' => 'totalPrice'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'itemSequenceNumber' => 'setItemSequenceNumber',
        'buyerProductIdentifier' => 'setBuyerProductIdentifier',
        'vendorProductIdentifier' => 'setVendorProductIdentifier',
        'title' => 'setTitle',
        'orderedQuantity' => 'setOrderedQuantity',
        'scheduledDeliveryShipment' => 'setScheduledDeliveryShipment',
        'giftDetails' => 'setGiftDetails',
        'netPrice' => 'setNetPrice',
        'taxDetails' => 'setTaxDetails',
        'totalPrice' => 'setTotalPrice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'itemSequenceNumber' => 'getItemSequenceNumber',
        'buyerProductIdentifier' => 'getBuyerProductIdentifier',
        'vendorProductIdentifier' => 'getVendorProductIdentifier',
        'title' => 'getTitle',
        'orderedQuantity' => 'getOrderedQuantity',
        'scheduledDeliveryShipment' => 'getScheduledDeliveryShipment',
        'giftDetails' => 'getGiftDetails',
        'netPrice' => 'getNetPrice',
        'taxDetails' => 'getTaxDetails',
        'totalPrice' => 'getTotalPrice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['itemSequenceNumber'] = $data['itemSequenceNumber'] ?? null;
        $this->container['buyerProductIdentifier'] = $data['buyerProductIdentifier'] ?? null;
        $this->container['vendorProductIdentifier'] = $data['vendorProductIdentifier'] ?? null;
        $this->container['title'] = $data['title'] ?? null;
        $this->container['orderedQuantity'] = $data['orderedQuantity'] ?? null;
        $this->container['scheduledDeliveryShipment'] = $data['scheduledDeliveryShipment'] ?? null;
        $this->container['giftDetails'] = $data['giftDetails'] ?? null;
        $this->container['netPrice'] = $data['netPrice'] ?? null;
        $this->container['taxDetails'] = $data['taxDetails'] ?? null;
        $this->container['totalPrice'] = $data['totalPrice'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['itemSequenceNumber'] === null) {
            $invalidProperties[] = "'itemSequenceNumber' can't be null";
        }
        if ($this->container['orderedQuantity'] === null) {
            $invalidProperties[] = "'orderedQuantity' can't be null";
        }
        if ($this->container['netPrice'] === null) {
            $invalidProperties[] = "'netPrice' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets itemSequenceNumber
     *
     * @return string
     */
    public function getItemSequenceNumber()
    {
        return $this->container['itemSequenceNumber'];
    }

    /**
     * Sets itemSequenceNumber
     *
     * @param string $itemSequenceNumber Numbering of the item on the purchase order. The first item will be 1, the second 2, and so on.
     *
     * @return self
     */
    public function setItemSequenceNumber($itemSequenceNumber)
    {
        $this->container['itemSequenceNumber'] = $itemSequenceNumber;

        return $this;
    }

    /**
     * Gets buyerProductIdentifier
     *
     * @return string|null
     */
    public function getBuyerProductIdentifier()
    {
        return $this->container['buyerProductIdentifier'];
    }

    /**
     * Sets buyerProductIdentifier
     *
     * @param string|null $buyerProductIdentifier Buyer's standard identification number (ASIN) of an item.
     *
     * @return self
     */
    public function setBuyerProductIdentifier($buyerProductIdentifier)
    {
        $this->container['buyerProductIdentifier'] = $buyerProductIdentifier;

        return $this;
    }

    /**
     * Gets vendorProductIdentifier
     *
     * @return string|null
     */
    public function getVendorProductIdentifier()
    {
        return $this->container['vendorProductIdentifier'];
    }

    /**
     * Sets vendorProductIdentifier
     *
     * @param string|null $vendorProductIdentifier The vendor selected product identification of the item.
     *
     * @return self
     */
    public function setVendorProductIdentifier($vendorProductIdentifier)
    {
        $this->container['vendorProductIdentifier'] = $vendorProductIdentifier;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Title for the item.
     *
     * @return self
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets orderedQuantity
     *
     * @return \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\ItemQuantity20211228
     */
    public function getOrderedQuantity()
    {
        return $this->container['orderedQuantity'];
    }

    /**
     * Sets orderedQuantity
     *
     * @param \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\ItemQuantity20211228 $orderedQuantity orderedQuantity
     *
     * @return self
     */
    public function setOrderedQuantity($orderedQuantity)
    {
        $this->container['orderedQuantity'] = $orderedQuantity;

        return $this;
    }

    /**
     * Gets scheduledDeliveryShipment
     *
     * @return \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\ScheduledDeliveryShipment20211228|null
     */
    public function getScheduledDeliveryShipment()
    {
        return $this->container['scheduledDeliveryShipment'];
    }

    /**
     * Sets scheduledDeliveryShipment
     *
     * @param \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\ScheduledDeliveryShipment20211228|null $scheduledDeliveryShipment scheduledDeliveryShipment
     *
     * @return self
     */
    public function setScheduledDeliveryShipment($scheduledDeliveryShipment)
    {
        $this->container['scheduledDeliveryShipment'] = $scheduledDeliveryShipment;

        return $this;
    }

    /**
     * Gets giftDetails
     *
     * @return \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\GiftDetails20211228|null
     */
    public function getGiftDetails()
    {
        return $this->container['giftDetails'];
    }

    /**
     * Sets giftDetails
     *
     * @param \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\GiftDetails20211228|null $giftDetails giftDetails
     *
     * @return self
     */
    public function setGiftDetails($giftDetails)
    {
        $this->container['giftDetails'] = $giftDetails;

        return $this;
    }

    /**
     * Gets netPrice
     *
     * @return \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\Money20211228
     */
    public function getNetPrice()
    {
        return $this->container['netPrice'];
    }

    /**
     * Sets netPrice
     *
     * @param \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\Money20211228 $netPrice netPrice
     *
     * @return self
     */
    public function setNetPrice($netPrice)
    {
        $this->container['netPrice'] = $netPrice;

        return $this;
    }

    /**
     * Gets taxDetails
     *
     * @return \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\TaxItemDetails20211228|null
     */
    public function getTaxDetails()
    {
        return $this->container['taxDetails'];
    }

    /**
     * Sets taxDetails
     *
     * @param \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\TaxItemDetails20211228|null $taxDetails taxDetails
     *
     * @return self
     */
    public function setTaxDetails($taxDetails)
    {
        $this->container['taxDetails'] = $taxDetails;

        return $this;
    }

    /**
     * Gets totalPrice
     *
     * @return \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\Money20211228|null
     */
    public function getTotalPrice()
    {
        return $this->container['totalPrice'];
    }

    /**
     * Sets totalPrice
     *
     * @param \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApi20211228\Model\Money20211228|null $totalPrice totalPrice
     *
     * @return self
     */
    public function setTotalPrice($totalPrice)
    {
        $this->container['totalPrice'] = $totalPrice;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


