<?php
/**
 * IncludedFeeDetail
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\ProductFeesApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\ProductFeesApi\Model;

use Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * IncludedFeeDetail Class Doc Comment
 *
 * @category Class
 * @description The type of fee, fee amount, and other details.
 * @package  Webcom\Amazon\Rest\ProductFeesApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class IncludedFeeDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'IncludedFeeDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'feeType' => 'string',
        'feeAmount' => '\Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType',
        'feePromotion' => '\Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType',
        'taxAmount' => '\Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType',
        'finalFee' => '\Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'feeType' => null,
        'feeAmount' => null,
        'feePromotion' => null,
        'taxAmount' => null,
        'finalFee' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'feeType' => 'FeeType',
        'feeAmount' => 'FeeAmount',
        'feePromotion' => 'FeePromotion',
        'taxAmount' => 'TaxAmount',
        'finalFee' => 'FinalFee'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'feeType' => 'setFeeType',
        'feeAmount' => 'setFeeAmount',
        'feePromotion' => 'setFeePromotion',
        'taxAmount' => 'setTaxAmount',
        'finalFee' => 'setFinalFee'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'feeType' => 'getFeeType',
        'feeAmount' => 'getFeeAmount',
        'feePromotion' => 'getFeePromotion',
        'taxAmount' => 'getTaxAmount',
        'finalFee' => 'getFinalFee'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['feeType'] = $data['feeType'] ?? null;
        $this->container['feeAmount'] = $data['feeAmount'] ?? null;
        $this->container['feePromotion'] = $data['feePromotion'] ?? null;
        $this->container['taxAmount'] = $data['taxAmount'] ?? null;
        $this->container['finalFee'] = $data['finalFee'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['feeType'] === null) {
            $invalidProperties[] = "'feeType' can't be null";
        }
        if ($this->container['feeAmount'] === null) {
            $invalidProperties[] = "'feeAmount' can't be null";
        }
        if ($this->container['finalFee'] === null) {
            $invalidProperties[] = "'finalFee' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets feeType
     *
     * @return string
     */
    public function getFeeType()
    {
        return $this->container['feeType'];
    }

    /**
     * Sets feeType
     *
     * @param string $feeType The type of fee charged to a seller.
     *
     * @return self
     */
    public function setFeeType($feeType)
    {
        $this->container['feeType'] = $feeType;

        return $this;
    }

    /**
     * Gets feeAmount
     *
     * @return \Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType
     */
    public function getFeeAmount()
    {
        return $this->container['feeAmount'];
    }

    /**
     * Sets feeAmount
     *
     * @param \Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType $feeAmount feeAmount
     *
     * @return self
     */
    public function setFeeAmount($feeAmount)
    {
        $this->container['feeAmount'] = $feeAmount;

        return $this;
    }

    /**
     * Gets feePromotion
     *
     * @return \Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType|null
     */
    public function getFeePromotion()
    {
        return $this->container['feePromotion'];
    }

    /**
     * Sets feePromotion
     *
     * @param \Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType|null $feePromotion feePromotion
     *
     * @return self
     */
    public function setFeePromotion($feePromotion)
    {
        $this->container['feePromotion'] = $feePromotion;

        return $this;
    }

    /**
     * Gets taxAmount
     *
     * @return \Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType|null
     */
    public function getTaxAmount()
    {
        return $this->container['taxAmount'];
    }

    /**
     * Sets taxAmount
     *
     * @param \Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType|null $taxAmount taxAmount
     *
     * @return self
     */
    public function setTaxAmount($taxAmount)
    {
        $this->container['taxAmount'] = $taxAmount;

        return $this;
    }

    /**
     * Gets finalFee
     *
     * @return \Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType
     */
    public function getFinalFee()
    {
        return $this->container['finalFee'];
    }

    /**
     * Sets finalFee
     *
     * @param \Webcom\Amazon\Rest\ProductFeesApi\Model\MoneyType $finalFee finalFee
     *
     * @return self
     */
    public function setFinalFee($finalFee)
    {
        $this->container['finalFee'] = $finalFee;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


