<?php
/**
 * GetInboundGuidanceResultV0
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\FulfillmentInboundApiV0
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model;

use \Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * GetInboundGuidanceResultV0 Class Doc Comment
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\FulfillmentInboundApiV0
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class GetInboundGuidanceResultV0 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetInboundGuidanceResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sKUInboundGuidanceList' => '\Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\SKUInboundGuidanceV0[]',
        'invalidSKUList' => '\Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\InvalidSKUV0[]',
        'aSINInboundGuidanceList' => '\Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\ASINInboundGuidanceV0[]',
        'invalidASINList' => '\Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\InvalidASINV0[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sKUInboundGuidanceList' => null,
        'invalidSKUList' => null,
        'aSINInboundGuidanceList' => null,
        'invalidASINList' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sKUInboundGuidanceList' => 'SKUInboundGuidanceList',
        'invalidSKUList' => 'InvalidSKUList',
        'aSINInboundGuidanceList' => 'ASINInboundGuidanceList',
        'invalidASINList' => 'InvalidASINList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sKUInboundGuidanceList' => 'setSKUInboundGuidanceList',
        'invalidSKUList' => 'setInvalidSKUList',
        'aSINInboundGuidanceList' => 'setASINInboundGuidanceList',
        'invalidASINList' => 'setInvalidASINList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sKUInboundGuidanceList' => 'getSKUInboundGuidanceList',
        'invalidSKUList' => 'getInvalidSKUList',
        'aSINInboundGuidanceList' => 'getASINInboundGuidanceList',
        'invalidASINList' => 'getInvalidASINList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sKUInboundGuidanceList'] = $data['sKUInboundGuidanceList'] ?? null;
        $this->container['invalidSKUList'] = $data['invalidSKUList'] ?? null;
        $this->container['aSINInboundGuidanceList'] = $data['aSINInboundGuidanceList'] ?? null;
        $this->container['invalidASINList'] = $data['invalidASINList'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sKUInboundGuidanceList
     *
     * @return \Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\SKUInboundGuidanceV0[]|null
     */
    public function getSKUInboundGuidanceList()
    {
        return $this->container['sKUInboundGuidanceList'];
    }

    /**
     * Sets sKUInboundGuidanceList
     *
     * @param \Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\SKUInboundGuidanceV0[]|null $sKUInboundGuidanceList A list of SKU inbound guidance information.
     *
     * @return self
     */
    public function setSKUInboundGuidanceList($sKUInboundGuidanceList)
    {
        $this->container['sKUInboundGuidanceList'] = $sKUInboundGuidanceList;

        return $this;
    }

    /**
     * Gets invalidSKUList
     *
     * @return \Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\InvalidSKUV0[]|null
     */
    public function getInvalidSKUList()
    {
        return $this->container['invalidSKUList'];
    }

    /**
     * Sets invalidSKUList
     *
     * @param \Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\InvalidSKUV0[]|null $invalidSKUList A list of invalid SKU values and the reason they are invalid.
     *
     * @return self
     */
    public function setInvalidSKUList($invalidSKUList)
    {
        $this->container['invalidSKUList'] = $invalidSKUList;

        return $this;
    }

    /**
     * Gets aSINInboundGuidanceList
     *
     * @return \Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\ASINInboundGuidanceV0[]|null
     */
    public function getASINInboundGuidanceList()
    {
        return $this->container['aSINInboundGuidanceList'];
    }

    /**
     * Sets aSINInboundGuidanceList
     *
     * @param \Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\ASINInboundGuidanceV0[]|null $aSINInboundGuidanceList A list of ASINs and their associated inbound guidance.
     *
     * @return self
     */
    public function setASINInboundGuidanceList($aSINInboundGuidanceList)
    {
        $this->container['aSINInboundGuidanceList'] = $aSINInboundGuidanceList;

        return $this;
    }

    /**
     * Gets invalidASINList
     *
     * @return \Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\InvalidASINV0[]|null
     */
    public function getInvalidASINList()
    {
        return $this->container['invalidASINList'];
    }

    /**
     * Sets invalidASINList
     *
     * @param \Webcom\Amazon\Rest\FulfillmentInboundApiV0\Model\InvalidASINV0[]|null $invalidASINList A list of invalid ASIN values and the reasons they are invalid.
     *
     * @return self
     */
    public function setInvalidASINList($invalidASINList)
    {
        $this->container['invalidASINList'] = $invalidASINList;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


