<?php
/**
 * RemovalShipmentItemAdjustmentV0
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\FinancesApiV0
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\FinancesApiV0\Model;

use \Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * RemovalShipmentItemAdjustmentV0 Class Doc Comment
 *
 * @category Class
 * @description Item-level information for a removal shipment item adjustment.
 * @package  Webcom\Amazon\Rest\FinancesApiV0
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class RemovalShipmentItemAdjustmentV0 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RemovalShipmentItemAdjustment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'removalShipmentItemId' => 'string',
        'taxCollectionModel' => 'string',
        'fulfillmentNetworkSKU' => 'string',
        'adjustedQuantity' => 'int',
        'revenueAdjustment' => '\Webcom\Amazon\Rest\FinancesApiV0\Model\CurrencyV0',
        'taxAmountAdjustment' => '\Webcom\Amazon\Rest\FinancesApiV0\Model\CurrencyV0',
        'taxWithheldAdjustment' => '\Webcom\Amazon\Rest\FinancesApiV0\Model\CurrencyV0'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'removalShipmentItemId' => null,
        'taxCollectionModel' => null,
        'fulfillmentNetworkSKU' => null,
        'adjustedQuantity' => 'int32',
        'revenueAdjustment' => null,
        'taxAmountAdjustment' => null,
        'taxWithheldAdjustment' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'removalShipmentItemId' => 'RemovalShipmentItemId',
        'taxCollectionModel' => 'TaxCollectionModel',
        'fulfillmentNetworkSKU' => 'FulfillmentNetworkSKU',
        'adjustedQuantity' => 'AdjustedQuantity',
        'revenueAdjustment' => 'RevenueAdjustment',
        'taxAmountAdjustment' => 'TaxAmountAdjustment',
        'taxWithheldAdjustment' => 'TaxWithheldAdjustment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'removalShipmentItemId' => 'setRemovalShipmentItemId',
        'taxCollectionModel' => 'setTaxCollectionModel',
        'fulfillmentNetworkSKU' => 'setFulfillmentNetworkSKU',
        'adjustedQuantity' => 'setAdjustedQuantity',
        'revenueAdjustment' => 'setRevenueAdjustment',
        'taxAmountAdjustment' => 'setTaxAmountAdjustment',
        'taxWithheldAdjustment' => 'setTaxWithheldAdjustment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'removalShipmentItemId' => 'getRemovalShipmentItemId',
        'taxCollectionModel' => 'getTaxCollectionModel',
        'fulfillmentNetworkSKU' => 'getFulfillmentNetworkSKU',
        'adjustedQuantity' => 'getAdjustedQuantity',
        'revenueAdjustment' => 'getRevenueAdjustment',
        'taxAmountAdjustment' => 'getTaxAmountAdjustment',
        'taxWithheldAdjustment' => 'getTaxWithheldAdjustment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['removalShipmentItemId'] = $data['removalShipmentItemId'] ?? null;
        $this->container['taxCollectionModel'] = $data['taxCollectionModel'] ?? null;
        $this->container['fulfillmentNetworkSKU'] = $data['fulfillmentNetworkSKU'] ?? null;
        $this->container['adjustedQuantity'] = $data['adjustedQuantity'] ?? null;
        $this->container['revenueAdjustment'] = $data['revenueAdjustment'] ?? null;
        $this->container['taxAmountAdjustment'] = $data['taxAmountAdjustment'] ?? null;
        $this->container['taxWithheldAdjustment'] = $data['taxWithheldAdjustment'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets removalShipmentItemId
     *
     * @return string|null
     */
    public function getRemovalShipmentItemId()
    {
        return $this->container['removalShipmentItemId'];
    }

    /**
     * Sets removalShipmentItemId
     *
     * @param string|null $removalShipmentItemId An identifier for an item in a removal shipment.
     *
     * @return self
     */
    public function setRemovalShipmentItemId($removalShipmentItemId)
    {
        $this->container['removalShipmentItemId'] = $removalShipmentItemId;

        return $this;
    }

    /**
     * Gets taxCollectionModel
     *
     * @return string|null
     */
    public function getTaxCollectionModel()
    {
        return $this->container['taxCollectionModel'];
    }

    /**
     * Sets taxCollectionModel
     *
     * @param string|null $taxCollectionModel The tax collection model applied to the item.  Possible values:  * MarketplaceFacilitator - Tax is withheld and remitted to the taxing authority by Amazon on behalf of the seller.  * Standard - Tax is paid to the seller and not remitted to the taxing authority by Amazon.
     *
     * @return self
     */
    public function setTaxCollectionModel($taxCollectionModel)
    {
        $this->container['taxCollectionModel'] = $taxCollectionModel;

        return $this;
    }

    /**
     * Gets fulfillmentNetworkSKU
     *
     * @return string|null
     */
    public function getFulfillmentNetworkSKU()
    {
        return $this->container['fulfillmentNetworkSKU'];
    }

    /**
     * Sets fulfillmentNetworkSKU
     *
     * @param string|null $fulfillmentNetworkSKU The Amazon fulfillment network SKU for the item.
     *
     * @return self
     */
    public function setFulfillmentNetworkSKU($fulfillmentNetworkSKU)
    {
        $this->container['fulfillmentNetworkSKU'] = $fulfillmentNetworkSKU;

        return $this;
    }

    /**
     * Gets adjustedQuantity
     *
     * @return int|null
     */
    public function getAdjustedQuantity()
    {
        return $this->container['adjustedQuantity'];
    }

    /**
     * Sets adjustedQuantity
     *
     * @param int|null $adjustedQuantity Adjusted quantity of removal shipmentItemAdjustment items.
     *
     * @return self
     */
    public function setAdjustedQuantity($adjustedQuantity)
    {
        $this->container['adjustedQuantity'] = $adjustedQuantity;

        return $this;
    }

    /**
     * Gets revenueAdjustment
     *
     * @return \Webcom\Amazon\Rest\FinancesApiV0\Model\CurrencyV0|null
     */
    public function getRevenueAdjustment()
    {
        return $this->container['revenueAdjustment'];
    }

    /**
     * Sets revenueAdjustment
     *
     * @param \Webcom\Amazon\Rest\FinancesApiV0\Model\CurrencyV0|null $revenueAdjustment revenueAdjustment
     *
     * @return self
     */
    public function setRevenueAdjustment($revenueAdjustment)
    {
        $this->container['revenueAdjustment'] = $revenueAdjustment;

        return $this;
    }

    /**
     * Gets taxAmountAdjustment
     *
     * @return \Webcom\Amazon\Rest\FinancesApiV0\Model\CurrencyV0|null
     */
    public function getTaxAmountAdjustment()
    {
        return $this->container['taxAmountAdjustment'];
    }

    /**
     * Sets taxAmountAdjustment
     *
     * @param \Webcom\Amazon\Rest\FinancesApiV0\Model\CurrencyV0|null $taxAmountAdjustment taxAmountAdjustment
     *
     * @return self
     */
    public function setTaxAmountAdjustment($taxAmountAdjustment)
    {
        $this->container['taxAmountAdjustment'] = $taxAmountAdjustment;

        return $this;
    }

    /**
     * Gets taxWithheldAdjustment
     *
     * @return \Webcom\Amazon\Rest\FinancesApiV0\Model\CurrencyV0|null
     */
    public function getTaxWithheldAdjustment()
    {
        return $this->container['taxWithheldAdjustment'];
    }

    /**
     * Sets taxWithheldAdjustment
     *
     * @param \Webcom\Amazon\Rest\FinancesApiV0\Model\CurrencyV0|null $taxWithheldAdjustment taxWithheldAdjustment
     *
     * @return self
     */
    public function setTaxWithheldAdjustment($taxWithheldAdjustment)
    {
        $this->container['taxWithheldAdjustment'] = $taxWithheldAdjustment;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


