<?php
/**
 * ShipmentDetails
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApiV20211228
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * The version of the OpenAPI document: 2021-12-28
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApiV20211228\Model;

use \Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * ShipmentDetails Class Doc Comment
 *
 * @category Class
 * @description Shipment details required for the shipment.
 * @package  Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApiV20211228
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class ShipmentDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShipmentDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'isPriorityShipment' => 'bool',
        'isScheduledDeliveryShipment' => 'bool',
        'isPslipRequired' => 'bool',
        'isGift' => 'bool',
        'shipMethod' => 'string',
        'shipmentDates' => '\Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApiV20211228\Model\ShipmentDates',
        'messageToCustomer' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'isPriorityShipment' => null,
        'isScheduledDeliveryShipment' => null,
        'isPslipRequired' => null,
        'isGift' => null,
        'shipMethod' => null,
        'shipmentDates' => null,
        'messageToCustomer' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'isPriorityShipment' => 'isPriorityShipment',
        'isScheduledDeliveryShipment' => 'isScheduledDeliveryShipment',
        'isPslipRequired' => 'isPslipRequired',
        'isGift' => 'isGift',
        'shipMethod' => 'shipMethod',
        'shipmentDates' => 'shipmentDates',
        'messageToCustomer' => 'messageToCustomer'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'isPriorityShipment' => 'setIsPriorityShipment',
        'isScheduledDeliveryShipment' => 'setIsScheduledDeliveryShipment',
        'isPslipRequired' => 'setIsPslipRequired',
        'isGift' => 'setIsGift',
        'shipMethod' => 'setShipMethod',
        'shipmentDates' => 'setShipmentDates',
        'messageToCustomer' => 'setMessageToCustomer'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'isPriorityShipment' => 'getIsPriorityShipment',
        'isScheduledDeliveryShipment' => 'getIsScheduledDeliveryShipment',
        'isPslipRequired' => 'getIsPslipRequired',
        'isGift' => 'getIsGift',
        'shipMethod' => 'getShipMethod',
        'shipmentDates' => 'getShipmentDates',
        'messageToCustomer' => 'getMessageToCustomer'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['isPriorityShipment'] = $data['isPriorityShipment'] ?? null;
        $this->container['isScheduledDeliveryShipment'] = $data['isScheduledDeliveryShipment'] ?? null;
        $this->container['isPslipRequired'] = $data['isPslipRequired'] ?? null;
        $this->container['isGift'] = $data['isGift'] ?? null;
        $this->container['shipMethod'] = $data['shipMethod'] ?? null;
        $this->container['shipmentDates'] = $data['shipmentDates'] ?? null;
        $this->container['messageToCustomer'] = $data['messageToCustomer'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['isPriorityShipment'] === null) {
            $invalidProperties[] = "'isPriorityShipment' can't be null";
        }
        if ($this->container['isPslipRequired'] === null) {
            $invalidProperties[] = "'isPslipRequired' can't be null";
        }
        if ($this->container['shipMethod'] === null) {
            $invalidProperties[] = "'shipMethod' can't be null";
        }
        if ($this->container['shipmentDates'] === null) {
            $invalidProperties[] = "'shipmentDates' can't be null";
        }
        if ($this->container['messageToCustomer'] === null) {
            $invalidProperties[] = "'messageToCustomer' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets isPriorityShipment
     *
     * @return bool
     */
    public function getIsPriorityShipment()
    {
        return $this->container['isPriorityShipment'];
    }

    /**
     * Sets isPriorityShipment
     *
     * @param bool $isPriorityShipment When true, this is a priority shipment.
     *
     * @return self
     */
    public function setIsPriorityShipment($isPriorityShipment)
    {
        $this->container['isPriorityShipment'] = $isPriorityShipment;

        return $this;
    }

    /**
     * Gets isScheduledDeliveryShipment
     *
     * @return bool|null
     */
    public function getIsScheduledDeliveryShipment()
    {
        return $this->container['isScheduledDeliveryShipment'];
    }

    /**
     * Sets isScheduledDeliveryShipment
     *
     * @param bool|null $isScheduledDeliveryShipment When true, this order is part of a scheduled delivery program.
     *
     * @return self
     */
    public function setIsScheduledDeliveryShipment($isScheduledDeliveryShipment)
    {
        $this->container['isScheduledDeliveryShipment'] = $isScheduledDeliveryShipment;

        return $this;
    }

    /**
     * Gets isPslipRequired
     *
     * @return bool
     */
    public function getIsPslipRequired()
    {
        return $this->container['isPslipRequired'];
    }

    /**
     * Sets isPslipRequired
     *
     * @param bool $isPslipRequired When true, a packing slip is required to be sent to the customer.
     *
     * @return self
     */
    public function setIsPslipRequired($isPslipRequired)
    {
        $this->container['isPslipRequired'] = $isPslipRequired;

        return $this;
    }

    /**
     * Gets isGift
     *
     * @return bool|null
     */
    public function getIsGift()
    {
        return $this->container['isGift'];
    }

    /**
     * Sets isGift
     *
     * @param bool|null $isGift When true, the order contain a gift. Include the gift message and gift wrap information.
     *
     * @return self
     */
    public function setIsGift($isGift)
    {
        $this->container['isGift'] = $isGift;

        return $this;
    }

    /**
     * Gets shipMethod
     *
     * @return string
     */
    public function getShipMethod()
    {
        return $this->container['shipMethod'];
    }

    /**
     * Sets shipMethod
     *
     * @param string $shipMethod Ship method to be used for shipping the order. Amazon defines ship method codes indicating the shipping carrier and shipment service level. To see the full list of ship methods in use, including both the code and the friendly name, search the 'Help' section on Vendor Central for 'ship methods'.
     *
     * @return self
     */
    public function setShipMethod($shipMethod)
    {
        $this->container['shipMethod'] = $shipMethod;

        return $this;
    }

    /**
     * Gets shipmentDates
     *
     * @return \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApiV20211228\Model\ShipmentDates
     */
    public function getShipmentDates()
    {
        return $this->container['shipmentDates'];
    }

    /**
     * Sets shipmentDates
     *
     * @param \Webcom\Amazon\Rest\VendorDirectFulfillmentOrdersApiV20211228\Model\ShipmentDates $shipmentDates shipmentDates
     *
     * @return self
     */
    public function setShipmentDates($shipmentDates)
    {
        $this->container['shipmentDates'] = $shipmentDates;

        return $this;
    }

    /**
     * Gets messageToCustomer
     *
     * @return string
     */
    public function getMessageToCustomer()
    {
        return $this->container['messageToCustomer'];
    }

    /**
     * Sets messageToCustomer
     *
     * @param string $messageToCustomer Message to customer for order status.
     *
     * @return self
     */
    public function setMessageToCustomer($messageToCustomer)
    {
        $this->container['messageToCustomer'] = $messageToCustomer;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


